//
//  MainMenuInteractor.swift
//  ProjectPPD
//
//  Created by Clinton de Sá Barreto Maciel on 06/02/19.
//  Copyright (c) 2019 Clinton de Sá. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMenuBusinessLogic {
    func connectionAccepted(request: MainMenu.ConnectionAccepted.Request)
}

protocol MainMenuDataStore {
    var oponent: (RPCHandler & RPCChatDelegate)? { get set }
}

class MainMenuInteractor: MainMenuBusinessLogic, MainMenuDataStore {
    var presenter: MainMenuPresentationLogic?
    var worker: MainMenuWorker?
    
    // MARK: DataStore
    
    var oponent: (RPCHandler & RPCChatDelegate)? = RPCHandler.sharedOponent
    
    // MARK: Connection accepted
    
    func connectionAccepted(request: MainMenu.ConnectionAccepted.Request) {
        if let username = request.playerUsername {
            oponent?.setOponentsOponentUsername(newUsername: username)
        }
        
        let response = MainMenu.ConnectionAccepted.Response(playerUsername: request.playerUsername)
        presenter?.presentConnectionAccepted(response: response)
    }
}



