//
//  MainMenuPresenter.swift
//  ProjectPPD
//
//  Created by Clinton de Sá Barreto Maciel on 06/02/19.
//  Copyright (c) 2019 Clinton de Sá. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMenuPresentationLogic {
    func presentConnecToNameServer(response: MainMenu.ConnectToNameServer.Response)
}

class MainMenuPresenter: MainMenuPresentationLogic {
    weak var viewController: MainMenuDisplayLogic?
    
    // MARK: Connect to name server
    
    func presentConnecToNameServer(response: MainMenu.ConnectToNameServer.Response) {
        let viewModel = MainMenu.ConnectToNameServer.ViewModel(username: response.username)
        viewController?.displayConnectToServer(viewModel: viewModel)
    }
}
