//
//  MainMenuViewController.swift
//  ProjectPPD
//
//  Created by Clinton de Sá Barreto Maciel on 06/02/19.
//  Copyright (c) 2019 Clinton de Sá. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SCLAlertView

protocol MainMenuDisplayLogic: class {
    func displayConnectionAccepted(viewModel: MainMenu.ConnectionAccepted.ViewModel)
}

class MainMenuViewController: UIViewController {
    
    // MARK: Static
    
    static let viewIdentifier = "MainMenuViewController"
    
    // MARK: VIP refences
    
    var interactor: MainMenuBusinessLogic?
    var router: (NSObjectProtocol & MainMenuRoutingLogic & MainMenuDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MainMenuInteractor()
        let presenter = MainMenuPresenter()
        let router = MainMenuRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: Control variables
    
    var alertResponder: SCLAlertViewResponder?
    
    // MARK: Actions
    
    @IBAction func searchForMatch(_ sender: Any) {
        ConnectionHandler.shared.set(newDelegate: self)
        let defaultPort = 8900
        ConnectionHandler.shared.connectSockets()
        
        alertResponder = AlertHelper.showWaiting(withTitle: "Esperando adversário", andSubTitle: "Estamos esperando um adversário na porta \(defaultPort)") {
            ConnectionHandler.shared.disconnectSockets()
        }
        
//        let timer = Timer(fire: Date().addingTimeInterval(5), interval: 5, repeats: true) { (timer) in
//            if let status = ConnectionHandler.shared.connectionStatus,
//                status == .connected {
//                timer.invalidate()
//                return
//            }
//
//            defaultPort += 1
//
//            if defaultPort > 8903 {
//                timer.invalidate()
//                self.alertResponder?.close()
//                return
//            }
//
//            ConnectionHandler.shared.disconnectSockets()
//            ConnectionHandler.shared.connectSockets(in: defaultPort)
//
//            self.alertResponder?.setSubTitle("Estamos esperando um adversário na porta \(defaultPort)")
//        }
//        timer.fire()
    }
    
    @IBAction func logInMatchAction(_ sender: Any) {
//        AlertHelper.showFieldAlert(withTitle: "Procurando adversário", andSubtitle: "Por favor defina a porta em que seu adversário se encontra") { (portString) in
//            if let portNumber = Int(portString) {
//                ConnectionHandler.shared.connectSockets(in: portNumber)
//            }
//        }
    }
}

extension MainMenuViewController: ConnectionHandlerDelegate {
    func startChat(username: String?) {
        let request = MainMenu.ConnectionAccepted.Request(playerUsername: username)
        interactor?.connectionAccepted(request: request)
    }
}

extension MainMenuViewController: MainMenuDisplayLogic {
    
    // MARK: Connection accepted
    
    func displayConnectionAccepted(viewModel: MainMenu.ConnectionAccepted.ViewModel) {
        let dispatchTime = DispatchTime.now() + 1
        DispatchQueue.main.asyncAfter(deadline: dispatchTime) {
            self.alertResponder?.close()
            print("Route to next game scene")
            self.router?.routeToGameplayFlux()
        }
    }
}
