//
//  MainMenuPresenter.swift
//  ProjectPPD
//
//  Created by Clinton de Sá Barreto Maciel on 06/02/19.
//  Copyright (c) 2019 Clinton de Sá. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMenuPresentationLogic {
    func presentConnectionAccepted(response: MainMenu.ConnectionAccepted.Response)
}

class MainMenuPresenter: MainMenuPresentationLogic {
    weak var viewController: MainMenuDisplayLogic?
    
    // MARK: Connection accepted
    
    func presentConnectionAccepted(response: MainMenu.ConnectionAccepted.Response) {
        var isValidUsername = false
        
        if let username = response.playerUsername,
            username != "" {
            isValidUsername = true
        }
        
        let viewModel = MainMenu.ConnectionAccepted.ViewModel(isValidUsername: isValidUsername)
        viewController?.displayConnectionAccepted(viewModel: viewModel)
    }
}
