//
//  ChatModels.swift
//  SocketIOPPDProject
//
//  Created by Clinton de Sá Barreto Maciel on 11/02/19.
//  Copyright (c) 2019 Clinton de Sá. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Chat {
    
    // MARK: Use cases
    
    enum SendMessage {
        struct Request {
            let message: String
        }
        struct Response {
            let success: Bool
        }
        struct ViewModel {
            let success: Bool
        }
    }
    
    enum RefreshMessages {
        struct Request {
        }
        struct Response {
            let username: String?
            let messages: ChatMessageList?
        }
        struct ViewModel {
            let messages: [Message]
        }
    }

}
